function [lidar, radar, radarMountingLocation, radarMountingAngles] = helperSetupSensors(egoUAV)
% helperSetupSensors Initialize and configure LiDAR and radar sensor systems
%
% Description:
%   Sets up and configures LiDAR and radar sensor systems for UAV perception.
%   Creates sensor objects with specified mounting positions, orientations,
%   and performance characteristics for environmental perception and obstacle
%   detection in autonomous navigation scenarios.
%
% Input Parameters:
%   egoUAV - Ego UAV platform object for sensor mounting reference
%
% Output Parameters:
%   lidar                 - Configured LiDAR sensor object for point cloud generation
%   radar                 - Configured radar sensor object for target detection
%   radarMountingLocation - Radar mounting position [x, y, z] relative to UAV
%   radarMountingAngles   - Radar mounting orientation [yaw, pitch, roll] in degrees
%
% Sensor Specifications:
%   LiDAR:
%     - Range: 100 meters maximum
%     - Field of View: 360° azimuth, 30° elevation (-15° to +15°)
%     - Resolution: 0.2° azimuth, 2° elevation
%     - Update Rate: 5 Hz
%     - Mounting: [0, 0, -3] meters (below UAV center)
%
%   Radar:
%     - Range: 2-200 meters
%     - Field of View: 180° azimuth, 90° elevation
%     - Resolution: 2° azimuth, 6° elevation, 4 meters range
%     - Update Rate: 5 Hz
%     - Detection Probability: 98%
%     - False Alarm Rate: 1e-7
%     - Mounting: [0, 0, -2] meters (below UAV center)
%
    % Setup sensor system
    
    %% LiDAR
    lidarOrient = [0 0 0];
    lidarSensor = uavLidarPointCloudGenerator("MaxRange", 100, ...
        "RangeAccuracy", 0.03, ...
        "ElevationLimits", [-15 15], ...
        "ElevationResolution", 2, ...
        "AzimuthLimits", [-180 180], ...
        "AzimuthResolution", 0.2, ...
        "UpdateRate", 5, ...
        "HasOrganizedOutput", false);
    
    lidar = uavSensor("Lidar", egoUAV, lidarSensor, ...
        "MountingLocation", [0 0 -3], ...
        "MountingAngles", lidarOrient);
    
    %% Radar
    radarMountingLocation = [0 0 -2];
    radarMountingAngles = [0 0 0];
    
    radar = radarDataGenerator("no scanning", "SensorIndex", 1, ...
        "FieldOfView", [180 90], ...
        "UpdateRate", 5, ...
        "HasElevation", true, ...
        "ElevationResolution", 6, ...
        "AzimuthResolution", 2, ...
        "RangeResolution", 4, ...
        "RangeLimits", [2 200], ...
        'ReferenceRange', 100, ...
        'ReferenceRCS', 5, ...
        'CenterFrequency', 24.55e9, ...
        'Bandwidth', 200e6, ...
        "TargetReportFormat", "Detections", ...
        "DetectionCoordinates", "Sensor rectangular", ...
        "DetectionProbability", 0.98, ...
        "HasFalseAlarms", false, ...
        "FalseAlarmRate", 1e-7, ...
        "MountingLocation", radarMountingLocation, ...
        "MountingAngles", radarMountingAngles);
end